[package]
name = "fake-it"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
with-bench = []

[dependencies]
log = "0.4.16"
env_logger = "0.9.0"
rand = "0.8.5"
regex = "1.5.5"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.79"
csv = "1.1.6"

[dev-dependencies]
